### ISSUE TITLE
Problems extracting the `PFMatrixList` from `JASPAR2024`

### ISSUE THREAD

**Issue by machlabd** [da-bar/JASPAR2024#2]
Hello,

Thank you for providing us with the `JASPAR` packages. We are using them in our own package `monaLisa` (https://github.com/fmicompbio/monaLisa) and have recently become aware of changes to `JASPAR2024` which are causing a function called `dumpJaspar()` in `monaLisa` to fail (https://github.com/fmicompbio/monaLisa/blob/f0d64586fc2ed8630640bbf3f7d27dd68ffa920d/R/motif_enrichment_HOMER.R#L96-L98). 

Specifically, what is failing is getting the `JASPAR` class object (along with the sqlite path) the traditional way we did using the `utils::getFromNamespace` function, to be able to use as input to `TFBSTools::getMatrixSet` and extract the `PFMatrixList`. Below is the way we currently get the `PFMatrixList` from a `JASPAR` package set by the user as input to the function:

```
> pkg <- "JASPAR2022" # character defined by user as input 
> mdb <- utils::getFromNamespace(pkg, ns = pkg)
> siteList22 <- TFBSTools::getMatrixSet(mdb, list(tax_group = "vertebrates"))
```

This approach currently allows us to generalize the extraction of the `PFMatrixList` object to any `JASPAR` package. With `JASPAR2024`, `utils::getFromNamespace("JASPAR2024", ns = "JASPAR2024")` returns a function. So we need to interact specifically with the package as follows to extract the `PFMatrixList`:

```
> jp24 <- JASPAR2024()
> sq24 <- RSQLite::dbConnect(RSQLite::SQLite(), db(jp24))
> siteList24 <- TFBSTools::getMatrixSet(sq24, list(tax_group = "vertebrates"))
```

We are wondering if you have thoughts or plans for how users can interact with `TFBSTools::getMatrixSet` (e.g. adding a method for the `JASPAR2024` class) that will allow us to continue to interact with the `JASPAR` databases in a general manner, or if you have other suggestions on how we can extract the needed `PFMatrixList` from `JASPAR2024`. We would ideally like to implement a good solution before the April 15 deadline when Bioc 3.18 freezes.

Thanks in advance!

Best wishes,
Dania

**Comment by da-bar** [comment]
Hi Dania,
First of all, I would like to apologise for my late reply to this.
The changes you mentioned were a requirement from the Bioconductor team, who suggested not to export the object into the namespace, but rather having a constructor method. I am planning on implementing a similar approach for other JASPAR releases as well and have a single package, which will be able to load all the versions based on the users choice, but also reflect that change in the TFBStools interface. Unfortunately, this requires substantial coordination with the TFBStools maintainer as well as adding a new package to Bioconductor, which I am afraid is not possible for the next Bioc release. My suggestion for a quick fix is to add JASPAR2024 if statement for now that will load it in the way you wrote above, and hopefully we will sort the interface issue soon. I am very sorry for the caused inconvenience.

**Comment by machlabd** [comment]
Hi Damir,

Thanks a lot for letting us know! And thank you for your efforts looking into this. We have implemented a fix for the current version of our package with an `if` statement as you mentioned. We can close this issue for now, and we will follow up with the implementations you mentioned in the future, and how to best use them in `monaLisa`.

Many thanks.

Best,
Dania
